---
- name: enable the ubuntu cloud archive
  hosts: all
  sudo: True
  gather_facts: False

  tasks:

    # https://wiki.ubuntu.com/ServerTeam/CloudArchive
  - name: add key to ubuntu-cloud-keyring
    apt: pkg={{ item }} update_cache=yes
    with_items:
      - python-software-properties
      - ubuntu-cloud-keyring

  - name: add havana repo
    apt_repository: repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/havana main"

  - name: update apt cache
    apt: update_cache=yes
