---
- name: Glance image services
  hosts: controller
  sudo: True
  gather_facts: True

  tasks:
    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-glance.html
  - name: ensure glance is installed
    apt: pkg=glance

  - name: ensure glance sqlite is deleted
    file: dest=/var/lib/glance/glance.sqlite state=absent

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/configure-glance-mysql.html
  - name: ensure glance database is present
    mysql_db: name=glance
    notify:
      - restart glance-registry

  - name: ensure glance database user is present
    mysql_user: name=glance host=$item password=${glance_db_password} priv=glance.*:ALL
    with_items:
      - $controller_ip
      - localhost

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/configure-glance-files.html
  - name: ensure glance-api.conf file is up to date
    template: src=templates/etc/glance/glance-api.conf dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0600 backup=yes
    notify:
    - restart glance-api

  - name: ensure glance-registry.conf file is up to date
    template: src=templates/etc/glance/glance-registry.conf dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0600 backup=yes
    notify:
    - restart glance-registry

  - name: initialize the database
    # FIXME
    # glance_manage: action=dbsync
    command: glance-manage db_sync


  handlers:
  - name: restart glance-registry
    service: name=glance-registry state=restarted

  - name: restart glance-api
    service: name=glance-api state=restarted


- name: Ensure cirros test image installed
  hosts: controller
  gather_facts: False
  tasks:

  - name: add cirros 0.3.1 image to glance
    glance_image: copy_from=http://cdn.download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img
                  name=cirros-0.3.1-x86_64 disk_format=qcow2 is_public=true container_format=bare
                  login_username=admin login_tenant_name=demo login_password=secrete
                  region_name=RegionOne auth_url=http://${controller_ip}:5000/v2.0

  - name: add cirros 0.3.0 image to glance
    glance_image: copy_from=http://cdn.download.cirros-cloud.net/0.3.0/cirros-0.3.0-x86_64-disk.img
                  name=cirros-0.3.0-x86_64 disk_format=qcow2 is_public=true container_format=bare
                  login_username=admin login_tenant_name=demo login_password=secrete
                  region_name=RegionOne auth_url=http://${controller_ip}:5000/v2.0
