---
- name: Glance image services
  hosts: controller
  sudo: True
  gather_facts: True

  tasks:
    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-glance.html
  - name: ensure glance is installed
    apt: pkg=glance

  - name: ensure glance sqlite is deleted
    file: dest=/var/lib/glance/glance.sqlite state=absent

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/configure-glance-mysql.html
  - name: ensure glance database is present
    mysql_db: name=glance
    notify:
      - restart glance-registry

  - name: ensure glance database user is present
    mysql_user: name=glance host=$item password=${glance_db_password} priv=glance.*:ALL
    with_items:
      - $controller_ip
      - localhost

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/configure-glance-files.html
  - name: ensure glance-api.conf file is up to date
    template: src=templates/etc/glance/glance-api.conf dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0600 backup=yes
    notify:
    - restart glance-api

  - name: ensure glance-registry.conf file is up to date
    template: src=templates/etc/glance/glance-registry.conf dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0600 backup=yes
    notify:
    - restart glance-registry

  - name: initialize the database
    # FIXME
    # glance_manage: action=dbsync
    command: glance-manage db_sync


  handlers:
  - name: restart glance-registry
    service: name=glance-registry state=restarted

  - name: restart glance-api
    service: name=glance-api state=restarted


  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/images-verifying-install.html
- name: Ensure cirros test image installed
  hosts: controller
  gather_facts: False
  tags:
    - image
  vars:
    img_name: cirros-0.3.1-x86_64
    img_url: http://cdn.download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img

  tasks:
  - name: ensure temporary image directory exists
    file: dest=/tmp/images state=directory
    tags: debug

  - name: ensure test image has been obtained
    get_url: url=$img_url dest=/tmp/images/$img_name
    tags: debug

  - name: add cirros image to glance
    #glance: name=$img_name file=/tmp/images/$img_name disk_format=qcow2 is_public=true user=admin tenant=demo password=secrete region=RegionOne auth_url=http://${controller_ip}:5000/v2.0
    #FIXME and remove tags
    command: glance --os-username admin --os-password secrete --os-tenant-name demo --os-auth-url http://10.0.10.10:5000/v2.0/ image-create --file /tmp/images/$img_name --disk-format qcow2 --is-public true --container-format bare --name cirros-0.3.1-x86_64
    tags: debug
