---
- name: add user vagrant to group neutron
  hosts: netnode
  user: vagrant
  sudo: True
  gather_facts: False
  tasks:

  - name: add user vagrant to group neutron
    user: name=vagrant append=yes groups=neutron


- name: add user vagrant to groups neutron and nova
  hosts:
   - controller
   - compute_nodes
  user: vagrant
  sudo: True
  gather_facts: False
  tasks:

  - name: add user vagrant to groups neutron and nova
    user: name=vagrant append=yes groups=neutron,nova


- name: add some shell aliases
  hosts: all
  user: vagrant
  sudo: True
  gather_facts: False
  tasks:

  - name: add alias to list openstack services
    lineinfile: name=/home/vagrant/.bashrc regexp='^alias osservices' 
                line="alias osservices='cd /etc/init.d; ls neutron* nova* openvswitch* cinder* glance* libvirt-bin 2>/dev/null; cd - >/dev/null'"
