---
- name: Neutron L3, DHCP, LBaaS and metadata agents
  hosts: netnode
  sudo: True
  tasks:

  - name: install the packages
    apt: name={{ item }}
    with_items:
      - neutron-l3-agent
      - neutron-dhcp-agent
      - neutron-lbaas-agent
      - neutron-metadata-agent

  - name: ensure neutron.conf is configured
    template: >
          src=templates/etc/neutron/neutron.conf.j2
          dest=/etc/neutron/neutron.conf
          owner=neutron group=neutron mode=0660 backup=yes
    notify:
      - restart l3 agent
      - restart dhcp agent
      - restart lbaas agent
      - restart metadata agent

  - name: ensure l3 agent is configured
    template: >
          src=templates/etc/neutron/l3_agent.ini.j2
          dest=/etc/neutron/l3_agent.ini
          owner=neutron group=neutron mode=0660 backup=yes
    notify: restart l3 agent

  - name: ensure dhcp agent is configured
    template: >
          src=templates/etc/neutron/dhcp_agent.ini.j2
          dest=/etc/neutron/dhcp_agent.ini
          owner=neutron group=neutron mode=0660 backup=yes
    notify: restart dhcp agent

  - name: ensure lbaas agent is configured
    template: >
          src=templates/etc/neutron/lbaas_agent.ini.j2
          dest=/etc/neutron/lbaas_agent.ini
          owner=neutron group=neutron mode=0660 backup=yes
    notify: restart lbaas agent

  - name: ensure metadata agent is configured
    template: >
          src=templates/etc/neutron/metadata_agent.ini.j2
          dest=/etc/neutron/metadata_agent.ini
          owner=neutron group=neutron mode=0660 backup=yes
    notify: restart metadata agent

  handlers:
    - name: restart l3 agent
      action: service name=neutron-l3-agent state=restarted

    - name: restart dhcp agent
      action: service name=neutron-dhcp-agent state=restarted

    - name: restart lbaas agent
      action: service name=neutron-lbaas-agent state=restarted

    - name: restart metadata agent
      action: service name=neutron-metadata-agent state=restarted
