---
- name: Quantum L3, DHCP, LBaaS and metadata agents
  hosts: netnode
  sudo: True
  tasks:

  - name: ensure ovs bridge br-ex present
    command: /usr/bin/ovs-vsctl -- --may-exist add-br br-ex

  - name: ensure br-ex has physical nic
    command: /usr/bin/ovs-vsctl -- --may-exist add-port br-ex {{ ex_net_nic }}

  - name: configure physical inteface for br-ex to be brought up at boot (1/2)
    template: >
          src=templates/etc/network/interfaces.d/ex-nic.j2
          dest=/etc/network/interfaces.d/ex-nic
          owner=root group=root mode=0644

  - name: configure physical inteface for br-ex to be brought up at boot (2/2)
    lineinfile: >
          dest=/etc/network/interfaces
          regexp='source /etc/network/interfaces.d/ex-nic'
          line='source /etc/network/interfaces.d/ex-nic'

  - name: bring up physical interface for br-ex now
    command: /sbin/ifup {{ ex_net_nic }}

  - name: install the packages
    apt: name={{ item }}
    with_items:
      - quantum-l3-agent
      - quantum-dhcp-agent
      - quantum-lbaas-agent
      - quantum-metadata-agent

  - name: ensure quantum.conf ok
    template: >
          src=templates/etc/quantum/quantum.conf
          dest=/etc/quantum/quantum.conf
          owner=quantum group=quantum mode=0660 backup=yes
    notify:
      - restart l3 agent
      - restart dhcp agent
      - restart lbaas agent
      - restart metadata agent

    # note: default lbaas_agent.ini works

  - name: ensure l3 agent is configured
    template: >
          src=templates/etc/quantum/l3_agent.ini
          dest=/etc/quantum/l3_agent.ini
          owner=quantum group=quantum mode=0660 backup=yes
    notify: restart l3 agent

  - name: ensure dhcp agent is configured
    template: >
          src=templates/etc/quantum/dhcp_agent.ini.j2
          dest=/etc/quantum/dhcp_agent.ini
          owner=quantum group=quantum mode=0660 backup=yes
    notify: restart dhcp agent

  - name: ensure metadata agent is configured
    template: >
          src=templates/etc/quantum/metadata_agent.ini.j2
          dest=/etc/quantum/metadata_agent.ini
          owner=quantum group=quantum mode=0660 backup=yes
    notify: restart metadata agent

  handlers:
    - name: restart l3 agent
      action: service name=quantum-l3-agent state=restarted

    - name: restart dhcp agent
      action: service name=quantum-dhcp-agent state=restarted

    - name: restart lbaas agent
      action: service name=quantum-lbaas-agent state=restarted

    - name: restart metadata agent
      action: service name=quantum-metadata-agent state=restarted
