---
- name: Quantum L3 and DHCP agents
  hosts: netnode
  sudo: True

  # if the l2 ovs agent is installed, then quantum.conf is ready

  tasks:
  - name: install the packages
    apt: name=$item
    with_items:
      - quantum-l3-agent
      - quantum-dhcp-agent

  - name: ensure l3 agent is configured
    template: >
          src=templates/etc/quantum/l3_agent.ini
          dest=/etc/quantum/l3_agent.ini
          owner=quantum group=quantum mode=0600
    notify: restart l3 agent

  - name: ensure udev rule to configure br-ex is in place
    copy: >
          src=files/etc/udev/rules.d/configure_br-ex.rules
          dest=/etc/udev/rules.d/configure_br-ex.rules
          owner=root group=root mode=0644

  - name: ensure udev script for br-ex is present
    template: >
          src=templates/etc/udev/configure_br-ex
          dest=/etc/udev/configure_br-ex
          owner=root group=root mode=0755

  - name: ensure ovs bridge for gateway br-ex present
    command: /usr/bin/ovs-vsctl -- --may-exist add-br br-ex

  - name: ensure br-ex has eth3 enslaved
    command: /usr/bin/ovs-vsctl -- --may-exist add-port br-ex eth3

  handlers:
    - name: restart l3 agent
      service: name=quantum-l3-agent state=restarted
