---
- name: Quantum L3 and DHCP agents
  hosts: netnode
  sudo: True

  # if the l2 ovs agent is installed, then quantum.conf is ready

  tasks:
  - name: install the packages
    apt: name=$item
    with_items:
      - quantum-l3-agent
      - quantum-dhcp-agent

  - name: ensure l3 agent is configured
    template: >
          src=templates/etc/quantum/l3_agent.ini
          dest=/etc/quantum/l3_agent.ini
          owner=quantum group=quantum mode=0600
    notify: restart l3 agent

  - name: ensure ovs bridge for gateway br-ex present
    command: /usr/bin/ovs-vsctl -- --may-exist add-br br-ex

  - name: ensure br-ex has eth3 enslaved
    command: /usr/bin/ovs-vsctl -- --may-exist add-port br-ex eth3

  # TODO IP config for br-ex should be done in /etc/network...

  - name: ensure br-ex has external IP
    command: /sbin/ip addr add ${br-ex_ip} dev br-ex
    ignore_errors: True

  - name: ensure br-ex is up
    command: /sbin/ip link set dev br-ex up

  handlers:
    - name: restart l3 agent
      service: name=quantum-l3-agent state=restarted
